moai:
  initialized: true
  initialized_at: '2025-12-19T00:00:00Z'
  version: 1.14.0
project:
  name: tally-node
  mode: personal
  description: ''
  created_at: '2026-01-21 03:41:17'
  optimized: false
  template_version: 1.14.0
